# Generated by Django 5.0.3 on 2024-03-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoconference_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
